# Author: Maxim Chudinov
# Description: start nginx container with zabbix-agent
#
version: '2'
services:
  nginx-agent:
    build: ./nginx/nginx_agent
    restart: on-failure
    logging: 
        options:
          max-size: '10m'
          max-file: '5'