version: '2.0'
services:

  mysql-zabbix-agent:
    build: ./mysql/agent
    # ports:
    #  - "10050:10050"
    environment:
     - ZBX_SERVER_HOST=zabbix-server
     - ZBX_ACTIVE_ALLOW=false 
    # - ZBX_HOSTNAME=mysql-zabbix-agent
    volumes: 
     - ./mysql/agent/.my.cnf:/var/lib/zabbix/.my.cnf
     - ./mysql/agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d

  mysql-server-master:
    #image: mysql:8.0
    #image: mysql:5.7.26
    image: mariadb:10.4
    #image: percona:8.0
    # ports:
    #  - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root_pwd 
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]
    volumes:
     - ./mysql/master:/etc/mysql/conf.d
     - ./mysql/master:/etc/my.cnf.d
    # - ./mysql/master/var/lib/mysql:/var/lib/mysql:rw
    #env_file:
    #- ./mysql/master/.env_db_mysql
    #stop_grace_period: 1m

  # mysql-server-master2:
    # #image: mysql:8.0
    # #image: mysql:5.7.26
    # image: mariadb:10.4
    # #image: percona:8.0
    # # ports:
    # #  - "3306:3306"
    # environment:
     # - MYSQL_ROOT_PASSWORD=root_pwd 
    # command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]
    # volumes:
     # - ./mysql/master2:/etc/mysql/conf.d
     # - ./mysql/master2:/etc/my.cnf.d
    # # - ./mysql/master/var/lib/mysql:/var/lib/mysql:rw
    # #env_file:
    # #- ./mysql/master/.env_db_mysql
    # stop_grace_period: 1m

  mysql-server-slave:
    #build: ./mysql/slave
    #image: mysql:8.0
    #image: mysql:5.7.26
    image: mariadb:10.4
    #image: percona:8.0
    # ports:
    #  - "3307:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root_pwd 
    #command: [rm, -f, /var/lib/mysql/auto.cnf]
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]
    volumes:
     - ./mysql/slave:/etc/mysql/conf.d
     - ./mysql/slave:/etc/my.cnf.d
     - ./mysql/slave/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # - ./mysql/slave/var/lib/mysql:/var/lib/mysql:rw
    #env_file:
    #- ./mysql/slave/.env_db_mysql_slave
    depends_on:
     - mysql-server-master

# networks:
 # default:
   # external:
     # name: zabbix42_zbx_net_backend
